### ISSUE TITLE
android/java_io.nit: can't compile separately

### ISSUE THREAD

**Issue by privat** [nitlang/nit#696]
Got compilation errors with

```
$ ./nitg ../lib/android/java_io.nit 
```
